# Generated by Django 3.2.12 on 2023-04-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20230426_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='access_date',
            new_name='date',
        ),
    ]
